FROM node:lts-alpine

WORKDIR /workspace

COPY package*.json .
RUN npm install
COPY . .

ARG VITE_BACKEND_URL
ARG VITE_PROFILE_PICTURE_URL
ARG VITE_MOVIE_POSTER_URL
ARG VITE_MOVIE_BACKDROP_URL
ARG VITE_BACKEND_URL

ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_PROFILE_PICTURE_URL=$VITE_PROFILE_PICTURE_URL
ENV VITE_MOVIE_POSTER_URL=$VITE_MOVIE_POSTER_URL
ENV VITE_MOVIE_BACKDROP_URL=$VITE_MOVIE_BACKDROP_URL
ENV VITE_TMDB_API_KEY=$VITE_TMDB_API_KEY
RUN npm run build

FROM nginx:latest
RUN rm -rf /usr/share/nginx/html/*
COPY --from=0 /workspace/dist/ /usr/share/nginx/html/
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]